export const assessments: any[] = [
  {
    id: "001",
    position: "Departure",
    date: "00/00/0000",
    instructor: "john doe",
    intensity: 4,
    objective1: "This is objective 1",
    objective2: "This is objective 2",
    objective3: "",
    a: 10,
    b: 10,
    c: 10,
    d: 10,
    e: 10,
    f: 10,
    g: 10,
    h: 10,
    i: 10,
    j: 10,
    safety: "pass",
    grade: 100,
    remarks:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur magna sapien, pellentesque eget viverra in, aliquam ac nulla. Fusce sed nulla id lectus accumsan mattis et a felis. ",
    edit: "Edit",
  },
  {
    id: "002",
    position: "Departure",
    date: "00/00/0000",
    instructor: "jane doe",
    intensity: 4,
    objective1: "This is objective 1",
    objective2: "",
    objective3: "",
    a: 10,
    b: 10,
    c: 10,
    d: 10,
    e: 10,
    f: 10,
    g: 10,
    h: 10,
    i: 10,
    j: 10,
    safety: "fail",
    grade: 100,
    remarks:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur magna sapien, pellentesque eget viverra in, aliquam ac nulla. Fusce sed nulla id lectus accumsan mattis et a felis. ",
    edit: "Edit",
  },
  {
    id: "003",
    position: "Departure",
    date: "00/00/0000",
    instructor: "john doe",
    intensity: 4,
    objective1: "This is objective 1",
    objective2: "",
    objective3: "This is objective 3",
    a: 10,
    b: 10,
    c: 10,
    d: 10,
    e: 10,
    f: 10,
    g: 10,
    h: 10,
    i: 10,
    j: 10,
    safety: "pass",
    grade: 100,
    remarks:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur magna sapien, pellentesque eget viverra in, aliquam ac nulla. Fusce sed nulla id lectus accumsan mattis et a felis. ",
    edit: "Edit",
  },
];
